### PR TITLE
Fix API server integration #560

### PR DESCRIPTION
**Pull request by sebastien-prudhomme**
API server need to know the CA that is used by the Stash operator, not the reverse case.

Seems that all other Appscode charts have the same issue.

### CODE REVIEW

**Comment by tamalsaha** [comment]
This is not needed. We use Kubernetes aggregation server feature to self-host admission webhooks.

Our setup is based on the work here: https://github.com/openshift/kubernetes-namespace-reservation . I have explained some of the details here: https://github.com/appscode/stash/issues/353#issuecomment-372040217 .

**Comment by sebastien-prudhomme** [comment]
@tamalsaha Your explaination on #353 is right : "EAS provides its side of the identify using CA that is provides to kube api server in the APIService cabundle"

but what is done in the Helm chart is wrong as the CA bundle provided to "APIService" resource is not the Extended API Server one but the API Server one.

Can you try the original Helm chart on your side with webhooks activated ?

**Comment by sebastien-prudhomme** [comment]
@tamalsaha Just look how it's done on the service-catalog Helm chart that certainly was used as a base for Stash Helm chart (i said that because of the same CA name which is "svc-cat"):

https://github.com/kubernetes-incubator/service-catalog/blob/master/charts/catalog/templates/apiregistration.yaml

**Comment by tamalsaha** [comment]
If you look at the diagram from #353 

```
kubectl -----(1)-----> Kube api server -----(2)-----> Extended api server (EAS)
```

`(2)` is defined as an `APIService`. And Chart uses
```
  service:
    namespace: {{ .Release.Namespace }}
    name: {{ template "stash.fullname" . }}
  caBundle: {{ b64enc $ca.Cert }}
```

For webhook we don't call the EAS directly, rather access it via `(1)`. That is why in Webhooks we use 

```
- name: restic.admission.stash.appscode.com
  clientConfig:
    service:
      namespace: default
      name: kubernetes
      path: /apis/admission.stash.appscode.com/v1alpha1/restics
    caBundle: {{ b64enc .Values.apiserver.ca }}
```

**Comment by tamalsaha** [comment]
The original yamls are based on https://github.com/openshift/kubernetes-namespace-reservation/blob/master/artifacts/kube-install/apiserver-list.yaml.template . Then I used the service-catalog to issue certs.

**Comment by tamalsaha** [comment]
If you have not already, read https://kubernetes.io/blog/2018/01/extensible-admission-is-beta/ post.

**Comment by tamalsaha** [comment]
The main reason we access webhooks  via `(1)` instead of directly going to `(2)` is related to how `Authentication and trust` is handled. From the post:

```
Because webhook admission plugins have a lot of power (remember, they get to see the API resource content of any request sent to them and might modify them for mutating plugins), it is important to consider:

- How individual API servers verify their connection to the webhook admission server
- How the webhook admission server authenticates precisely which API server is contacting it
- Whether that particular API server has authorization to make the request There are three major categories of connection:
  - A. From kube-apiserver or extension-apiservers to externally hosted admission webhooks (webhooks not hosted in the cluster)
  - B. From kube-apiserver to self-hosted admission webhooks
  - C. From extension-apiservers to self-hosted admission webhooks To support these categories, the webhook admission plugins accept a kubeconfig file which describes how to connect to individual servers. For interacting with externally hosted admission webhooks, there is really no alternative to configuring that file manually since the authentication/authorization and access paths are owned by the server you’re hooking to.
```

I numbered the types of connections for ease of explanation.

Type A connections don't happen here since we are using self-hosted webhooks.

Type B connections happen when Webhooks are implemented for Core api types or CRD types using EAS. Here kube-apiserver itself makes a call to itself (not the service in ValidationWebhookConfiguration). kube-apiserver has a special case when it calls to itself and uses a internally generated root token. This is the case that affects Stash since we write ValidationWebhooks for Stash CRD types and MutatingWebhooks for Core Kubernetes types (like Deployment etc.).

Type C connections happen when the Resource type itself is implemented using EAS. For example Service-Catalog uses EAS to implement it's api types. Say, we want to write a Webhook for one of these types, say, `ClusterServiceBroker`. Now, the Service-catalog EAS has to make the webhook call. Now, if SVC-CAT EAS was making the calls to webhook EAS directly (path `(2)`), SVC-CAT will need a client cert for this webhooks EAS. In fact, SVC-CAT will need one client cert for each of the webhooks implemented for it's api types. And this will become unmanageable. A neat trick to avoid this problem is SVC-CAT EAS to call the kube-apiserver (since SVC-CAT EAS already has a valid serviceaccount token for kube-apiserver). Given SVC-CAT EAS has [permission](https://github.com/openshift/kubernetes-namespace-reservation/blob/master/artifacts/kube-install/rbac-list.yaml#L35), it can make webhooks calls without any problem. The nice thing about this setup is that this can be done when webhook is installed without touching anything about the SVC-CAT EAS installation.

**Comment by tamalsaha** [comment]
The main reason we access webhooks  via `(1)` instead of directly going to `(2)` is related to how `Authentication and trust` is handled. From the post:

```
Because webhook admission plugins have a lot of power (remember, they get to see the API resource content of any request sent to them and might modify them for mutating plugins), it is important to consider:

- How individual API servers verify their connection to the webhook admission server
- How the webhook admission server authenticates precisely which API server is contacting it
- Whether that particular API server has authorization to make the request There are three major categories of connection:
  - A. From kube-apiserver or extension-apiservers to externally hosted admission webhooks (webhooks not hosted in the cluster)
  - B. From kube-apiserver to self-hosted admission webhooks
  - C. From extension-apiservers to self-hosted admission webhooks To support these categories, the webhook admission plugins accept a kubeconfig file which describes how to connect to individual servers. For interacting with externally hosted admission webhooks, there is really no alternative to configuring that file manually since the authentication/authorization and access paths are owned by the server you’re hooking to.
```

I numbered the types of connections for ease of explanation.

Type A connections don't happen here since we are using self-hosted webhooks.

Type B connections happen when Webhooks are implemented for Core api types or CRD types using EAS. Here kube-apiserver itself makes a call to itself (not the service in ValidationWebhookConfiguration). kube-apiserver has a special case when it calls to itself and uses a internally generated root token. This is the case that affects Stash since we write ValidationWebhooks for Stash CRD types and MutatingWebhooks for Core Kubernetes types (like Deployment etc.). There was a bug in this code path prior to 1.9.8 which will cause `Unauthorized` error in case of multi-master setup https://gist.github.com/tamalsaha/78b772f6f0a28d7725221e76b3e48611.

Type C connections happen when the Resource type itself is implemented using EAS. For example Service-Catalog uses EAS to implement it's api types. Say, we want to write a Webhook for one of these types, say, `ClusterServiceBroker`. Now, the Service-catalog EAS has to make the webhook call. Now, if SVC-CAT EAS was making the calls to webhook EAS directly (path `(2)`), SVC-CAT will need a client cert for this webhooks EAS. In fact, SVC-CAT will need one client cert for each of the webhooks implemented for it's api types. And this will become unmanageable. A neat trick to avoid this problem is SVC-CAT EAS to call the kube-apiserver (since SVC-CAT EAS already has a valid serviceaccount token for kube-apiserver). Given SVC-CAT EAS has [permission](https://github.com/openshift/kubernetes-namespace-reservation/blob/master/artifacts/kube-install/rbac-list.yaml#L35), it can make webhooks calls without any problem. The nice thing about this setup is that this can be done when webhook is installed without touching anything about the SVC-CAT EAS installation.

Type B connections will face similar problem of requiring different client certs if it webhooks EAS is called directly via `(2)` for core api types and CRDs.

This is why we use path `(1)` to access self-hosted webhooks instead of directly calling the webhook EAS via `(2)`.

**Comment by sebastien-prudhomme** [comment]
Ok, thanks for taking time answering. Will read it completely when i'll be back to work.

**Comment by sebastien-prudhomme** [comment]
Ok i don't have the bug #560 now with the latest Helm chart in master branch.

Strange because i don't set a value for apiserver ca, which is now "not-ca-cert" by default.

I've tried to do a "kubectl edit" on an exiting Restic resource by providing a wrong configuration and the validating webhook works fine: admission webhook "restic.admission.stash.appscode.com" denied the request: spec.schedule  is invalid. Reason: Expected 5 or 6 fields, found 0: 

@tamalsaha I've seen that the cert-manager Helm chart is using an helper cronjob to setup all the  caBundles. Will it be possible to use that helper in stash Helm chart?

See there: https://github.com/jetstack/cert-manager/blob/master/contrib/charts/cert-manager/webhook/templates/ca-sync.yaml

**Comment by tamalsaha** [comment]
We set the CA bundle automatically inside the operator https://github.com/appscode/stash/pull/591/files#diff-3c862eb54a8e0e161b534e0c67e5379eR98 (code pushed in master branch).

https://github.com/appscode/kutil/blob/master/admissionregistration/v1beta1/validatingwebhookconfiguration.go#L125

Separate cron jobs are not needed.

**Pull request closed without merging**
